package com.busco.busco.enums;

public enum CarExtras {
    CLIMATE_CONTROL,
    FOUR_WHEEL_DRIVE,
    LEATHER_SEATS,
    HEATED_SEATS,
    SUNROOF,
    NAVIGATION_SYSTEM,
    BLUETOOTH,
    PARKING_SENSORS,
    REAR_CAMERA,
    CRUISE_CONTROL,
    TINTED_WINDOWS,
    LED_HEADLIGHTS,
    ADAPTIVE_CRUISE_CONTROL,
    BLIND_SPOT_MONITOR,
    LANE_KEEP_ASSIST,
    KEYLESS_ENTRY,
    REMOTE_START,
    PREMIUM_AUDIO_SYSTEM,
    AUTOMATIC_HEADLIGHTS
}
